{% set major_minor = "2.62" %}
{% set version = major_minor + ".0" %}
{% set sha256 = "36659f13cc73282392d1305858f3bbca46fbd1ce2f078cc9db8b9f79b2e93cfe" %}
{% if linux %}
    {% set libext = ".so" %}
{% else %}
    {% set libext = ".dylib" %}
{% endif %}

package:
  name: glibmm
  version: {{ version }}

source:
  fn: glibmm-{{ version }}.tar.xz
  url: http://ftp.gnome.org/pub/GNOME/sources/glibmm/{{ major_minor }}/glibmm-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 1000
  skip: true  # [win]

requirements:
  build:
    - make
    - pkg-config
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libsigcpp
    - glib
    - xz
  run:
    - libsigcpp
    - glib

test:
  commands:
    - test -f ${PREFIX}/lib/libgiomm-2.4{{ libext }}
    - test -f ${PREFIX}/lib/libglibmm-2.4{{ libext }}
    - test -f ${PREFIX}/lib/libglibmm_generate_extra_defs-2.4{{ libext }}

about:
  home: http://www.gtkmm.org
  license: LGPL v2.1
  license_family: GPL
  license_file: COPYING
  summary: "This is glibmm, a C++ API for parts of glib that are useful for C++."

extra:
  recipe-maintainers:
    - scopatz
