# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "3wT/XLMmuobFowtOh+2IvoJtGvB7VplbReIyhM1bCXPdOsVM0Nj1YkLJmRRt/qUr/yyJc3UO3Mm9W6K+eN1tFcEN0R5jaMjaIQpUhzHj1DJxxyNBcrvRDBP3MWmiYE+kcXYh/S2xGsBvemuGe6fdr4BrUme+daapGhTrw4Lq9OXLIrXZ4ktn4dV0KT1XCUitbQ6U4lPTjWTMpOItNcDXx7Iw0KM0FS83lBJevRWkrmHNxYLGq9xqsZVJAltoDHfARfimATOBP8cbkdB7rpM8z0x5Ilef5rqvrbRpWZw3Dwsc0on6c9KM+8aozjAeKFMcM/CnKZb/e+khvlcrQ6NRkmIupTIdT7g1rMQbohuq5+SlLdSTSChd3ySnwiMFpbBL+c8J3v8Zkq8pcX5H2Mfu+nzuDyC+EFwWeaeOVjUPF70OYrSCGQj0Vph340eRAnm66LZNFDEmXSb6Edg5rzK3YDgZdzuiFQ4gM1lmck3AGC39EZyrSTNm/zZjffr7HU4R+bdKw2+wRE+IBMfqwuLx7UGzTXfnzISsp9kBwGFgCCAAmQdDVsHznRNTmFxEFwDCjqRXc2ziM+v9JDyiT8ek4rT+4Rh0rHYDKzONdwG8Z4fcW5b5oXajRe9sOlaxrsZf3kJdMeH+0rCbS3v9V6MTcQJVT/zuTD0t3q7Jca0dszE="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
