travis:
  secure:
    BINSTAR_TOKEN: vy+LrSpckDhKlpeqqQPP+596b56iB6FCE7bI/m5J29U1EVe+2WX/G7JQW629V8dO1TbtNMJYeC2+TC97WSf8WQa1L05oJlexnpsRqXtZ0k+Ac6tu5uIkzUO4s327q6NxspHDsaSttG6rEgtsFYm/5S+4Ae/bT31guNk1l7dfgg0XXuzSAFnz0HQoP/APROSOU+2GqnHe7sZEhQCmX2BDTvMQn5BbQKmiiif9P0HKBqY3kpQiLa/mwyTcTbtTpfwbjG7TfGp0hvk38OiZUTh/25my52bwek9etdP24YwJysTX5ZfBhIhOgfulvCCbm+d7PcVVi0WkRicl/JyUwZZqk8gL28HfZVJ1hq7Y/9OZWmXKGHVovj4HEjQhErZFW/DLKQ/9BLAs0h9N0xC55bTIKslEPeArZ4XqKyv3a1O2AlxoL9zHt6hyzCxwaJZxnSop8Iq4w3CRyaEcbCYiuCODb0cLYzHUwD6KE9+Ncx/FaFcnfA43OfaTGcTbjeSLOxccRSOZXSmul7GuRpPe2XHtGaMQnflExaIRkAd8TIvpr+en+RwzeYi3VOZBe8aLNevpdSlZ82v5qB6Fj6uo0Hb8PnNzpSkVzXERR7/IxJ8/AJfJvcb6QMJdkes7dVPjyczAKShCaiB4VzJrMtzPc0+wRXPWuT1RR6XKCiqiZso4bFE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
